---
title: "airbnb_eda"
author: "Ningze Zu"
date: "11/16/2018"
output:
  pdf_document: default
  word_document: default
  html_document: default
---
## Abstract

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,out.width="0.9\\linewidth",dev="png",fig.align  = 'center')
pacman::p_load(ggplot2,knitr,arm,data.table,foreign,gridExtra,car,stringr,rstan,rstanarm,zoo)
library(tidyverse)
library(leaflet)
library(RColorBrewer)
la <- read.csv("la.csv")
ny <- read.csv("ny.csv")
van <- read.csv("van.csv")
sea <- read.csv("sea.csv")
airbnb_pre <- rbind(la, ny, van, sea)
airbnb_pre2 <- read.csv("air.csv")
airbnb_pre2 <- airbnb_pre2 %>% filter(price > 0 & price <=5000)

#airbnb_pre2 <- airbnb_pre2 %>% filter(price >= 80 & price <= 5000)

```

### Data Cleaning
```{r}
##Data Cleaning 
##Separte four cities and Add city name with new variable "Area" 
airbnb_la <- airbnb_pre2 %>% filter(str_detect(street, "CA")) 
airbnb_la$Area <- rep("Los Angelas",nrow(airbnb_la))
airbnb_ny <- airbnb_pre2 %>% filter(str_detect(street, "NY"))
airbnb_ny$Area <- rep("New York",nrow(airbnb_ny))
airbnb_se <- airbnb_pre2 %>% filter(str_detect(street, "WA"))
airbnb_se$Area <- rep("Seattle",nrow(airbnb_se))
airbnb_va <- airbnb_pre2 %>% filter(str_detect(street, "Canada"))
airbnb_va$Area <- rep("Vancouver",nrow(airbnb_va))
```

### EDA

#### Price Distribution
```{r}
#Price Distribution - LA
#0-1000
airbnb_la_1 <- airbnb_la %>% filter(price <= 1000)
ggplot(airbnb_la_1, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 10) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(0, 1000, by = 100)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in LA($0 ~$1000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 
#1000-5000
airbnb_la_2 <- airbnb_la %>% filter(price > 1000)
ggplot(airbnb_la_2, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 100) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(1000, 5000, by = 500)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in LA($1000 ~$5000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 


#Price Distribution - NY
#0-1000
airbnb_ny_1 <- airbnb_ny %>% filter(price <= 1000)
ggplot(airbnb_ny_1, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 10) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(0, 1000, by = 100)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in NYC($0 ~$1000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 
#1000-5000
airbnb_ny_2 <- airbnb_ny %>% filter(price > 1000)
ggplot(airbnb_ny_2, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 100) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(1000, 5000, by = 500)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in NYC($1000 ~$5000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 



#Price Distribution - SEATTLE
#0-1000
airbnb_se_1 <- airbnb_se %>% filter(price <= 1000)
ggplot(airbnb_se_1, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 10) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(0, 1000, by = 100)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in Seattle($0 ~$1000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 
#1000-5000
airbnb_se_2 <- airbnb_se %>% filter(price > 1000)
ggplot(airbnb_se_2, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 100) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(1000, 5000, by = 500)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in Seattle($1000 ~$5000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5))



#Price Distribution - Vancouver
#0-1000
airbnb_va_1 <- airbnb_va %>% filter(price <= 1000)
ggplot(airbnb_va_1, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 10) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(0, 1000, by = 100)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in Vancouver($0 ~$1000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 
#1000-5000
airbnb_va_2 <- airbnb_va %>% filter(price > 1000)
ggplot(airbnb_va_2, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 100) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(1000, 5000, by = 500)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution in Vancouver($1000 ~$5000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
##price distribution in all four cities
##0~1000
airbnb_pre2_1 <- airbnb_pre2 %>% filter(price > 0 & price <= 1000)
ggplot(airbnb_pre2_1, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 10) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(0, 1000, by = 100)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution($0 ~$1000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5)) 

#500~1000
airbnb_pre2_2 <- airbnb_pre2 %>% filter(price > 1000 & price <= 5000)
ggplot(airbnb_pre2_2, aes(price, fill = room_type)) + 
  geom_histogram(binwidth = 10) + theme_light() +   
  scale_fill_brewer(palette = "RdPu") + 
  scale_x_continuous(name ="Price ($)", breaks = seq(1000, 5000, by = 1000)) + 
  scale_y_continuous(name="Frequency of Price ")+ 
  ggtitle("Price Distribution($1000 ~$5000)") + 
  theme(axis.title.x = element_text(face="bold",  size=12), 
        axis.title.y = element_text(face="bold",  size=12),
        plot.title = element_text(size=14, face="bold"),  
        axis.text.x  = element_text(vjust=0.5, size=10)) +
  theme(plot.title = element_text(hjust = 0.5))
```

## Price ($0 ~ $1000)

### Price over Bedrooms 
```{r}
##bedroom ~ price in LA
airbnb_la_bed <- airbnb_la %>% filter(price > 0 & price <= 1000)
bedroom_la <- airbnb_la_bed %>% dplyr::select(price, bedrooms)
bedroom_la <- bedroom_la  %>% group_by(bedrooms) %>% summarise(mean_price = mean(price))
#barplot
ggplot(bedroom_la, aes(y=mean_price, x=bedrooms,fill=as.factor(bedrooms))) + 
      geom_bar(stat="identity", fill="pink") +  
      scale_x_continuous(name ="No. of Bedrooms", breaks = seq(0, 10, by = 1)) +   
      scale_y_continuous(name = "Mean price", breaks = seq(0, 1000, by = 100)) + theme_bw() + 
      ggtitle("Price over different number of bedrooms in LA") +
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))


##bedroom ~ price in NY
airbnb_ny_bed <- airbnb_ny %>% filter(price > 0 & price <= 1000)
bedroom_ny <- airbnb_ny_bed %>% dplyr::select(price, bedrooms)
bedroom_ny <- bedroom_ny  %>% group_by(bedrooms) %>% summarise(mean_price = mean(price))
#barplot
ggplot(bedroom_ny, aes(y=mean_price, x=bedrooms,fill=as.factor(bedrooms))) + 
      geom_bar(stat="identity", fill="pink") +  
      scale_x_continuous(name ="No. of Bedrooms", breaks = seq(0, 11, by = 1)) +   
      scale_y_continuous(name = "Mean price", breaks = seq(0, 1000, by = 100))+ theme_bw() +
      ggtitle("Price over different number of bedrooms in NYC") + 
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))


##bedroom ~ price in SE
airbnb_se_bed <- airbnb_se %>% filter(price > 0 & price <= 1000)
bedroom_se <- airbnb_se_bed %>% dplyr::select(price, bedrooms)
bedroom_se <- bedroom_se  %>% group_by(bedrooms) %>% summarise(mean_price = mean(price))
#barplot
ggplot(bedroom_se, aes(y=mean_price, x=bedrooms,fill=as.factor(bedrooms))) + 
      geom_bar(stat="identity", fill="pink") +  
      scale_x_continuous(name = "No. of Bedrooms", breaks = seq(0, 10, by = 1)) +   
      scale_y_continuous(name = "Mean price", breaks = seq(0, 1000, by = 100))+ theme_bw()+
      ggtitle("Price over different number of bedrooms in Seattle") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))


##bedroom ~ price in VA
airbnb_va_bed <- airbnb_va %>% filter(price > 0 & price <= 1000)
bedroom_va <- airbnb_va_bed %>% dplyr::select(price, bedrooms)
bedroom_va <- bedroom_va  %>% group_by(bedrooms) %>% summarise(mean_price = mean(price))
#barplot
ggplot(bedroom_va, aes(y=mean_price, x=bedrooms,fill=as.factor(bedrooms))) + 
      geom_bar(stat="identity", fill="pink") +  
      scale_x_continuous(name ="No. of Bedrooms", breaks = seq(0, 9, by = 1)) +   
      scale_y_continuous(name = "Mean price", breaks = seq(0, 1000, by = 100))+ theme_bw() +
      ggtitle("Price over different number of bedrooms in Vancouver") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))
```

### Geom smooth line ~ bedrooms/bathrooms/accommodates/
```{r}
airbnb_pre2_1 <- airbnb_pre2 %>% filter(price > 0 & price <= 1000)
ggplot(airbnb_pre2_1, aes(x=bedrooms, y=price)) + geom_point() + 
      geom_smooth(method = "lm") + theme_bw() + 
      ggtitle("Price over number of bedrooms")+  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))
ggplot(airbnb_pre2_1, aes(x=bathrooms, y=price)) + geom_point() + 
      geom_smooth(method = "lm") + theme_bw() + 
      ggtitle("Price over number of bathrooms")+  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))
ggplot(airbnb_pre2_1, aes(x=accommodates, y=price)) + geom_point() + 
      geom_smooth(method = "lm") + theme_bw() + 
      ggtitle("Price over number of accommodates")+  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))

```

### Price over Different Neighbourhoods
```{r,fig.width=11,fig.height=6}
###LA neighbourhood ~ Price
###since LA has 587 neighbourhood, I decide to use city as alternative choice.
airbnb_la_nei <- airbnb_la %>% filter(price > 0 & price <= 1000)
neigh_la <- airbnb_la_nei %>% dplyr::select(price, neighbourhood_cleansed)
neigh_la <- neigh_la  %>% group_by(neighbourhood_cleansed) %>% summarise(mean_price = mean(price))
ggplot(neigh_la, aes(y=mean_price, x=neighbourhood_cleansed,fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink") +  
      scale_x_discrete(name ="Neighbourhood in LA") +   
      scale_y_continuous(name = "Mean price", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in LA") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))

#unique(airbnb_la$city)



###Seattle Neightbourhood ~ Price
airbnb_se_nei <- airbnb_se %>% filter(price > 0 & price <= 1000)
neigh_se <- airbnb_se_nei %>% dplyr::select(price, neighbourhood_cleansed)
neigh_se <- neigh_se  %>% group_by(neighbourhood_cleansed) %>% summarise(mean_price = mean(price))
ggplot(neigh_se, aes(y=mean_price, x = 
                     reorder(x=neighbourhood_cleansed,-mean_price),
                     fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Neighbourhood in Seattle") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in Seattle") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))


###NYC Neightbourhood ~ Price
airbnb_ny_nei <- airbnb_ny %>% filter(price > 0 & price <= 1000)
neigh_ny <- airbnb_ny_nei %>% dplyr::select(price, neighbourhood_cleansed)
neigh_ny <- neigh_ny  %>% group_by(neighbourhood_cleansed) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))

g1 <- ggplot(subset(neigh_ny, mean_price %in% mean_price[1:60]), aes(y=mean_price,
                       reorder(x=neighbourhood_cleansed,-mean_price),
                       fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Neighbourhood in NYC") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in NYC(1)") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))


g2 <- ggplot(subset(neigh_ny, mean_price %in% mean_price[61:120]), aes(y=mean_price,
                       reorder(x=neighbourhood_cleansed,-mean_price),
                       fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Neighbourhood in NYC") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in NYC(2)") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))

g3 <- ggplot(subset(neigh_ny, mean_price %in% mean_price[121:180]), aes(y=mean_price,
                       reorder(x=neighbourhood_cleansed,-mean_price),
                       fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Neighbourhood in NYC") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in NYC(3)") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))

g4 <- ggplot(subset(neigh_ny, mean_price %in% mean_price[181:226]), aes(y=mean_price,
                       reorder(x=neighbourhood_cleansed,-mean_price),
                       fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Neighbourhood in NYC") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in NYC(4)") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))
g1
g2
g3
g4
#grid.arrange(g1,g2,g3,g4)


###Vancouver Neightbourhood ~ Price
airbnb_va_nei <- airbnb_va %>% filter(price > 0 & price <= 1000)
neigh_va <- airbnb_va_nei %>% dplyr::select(price, neighbourhood_cleansed)
neigh_va <- neigh_va  %>% group_by(neighbourhood_cleansed) %>% summarise(mean_price = mean(price))
ggplot(neigh_va, aes(y=mean_price, x = 
                     reorder(x=neighbourhood_cleansed,-mean_price),
                     fill=as.factor(neighbourhood_cleansed))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Neighbourhood in Vancouver") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different neighbourhood in Vancouver") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 10),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))
```

### Price ~ SuperHost
```{r}
airbnb_la_bed <- airbnb_la %>% filter(price > 0 & price <= 1000)
airbnb_la_bed <- airbnb_la_bed %>% na.omit(host_is_superhost)
ggplot(airbnb_la_bed, aes(x=host_is_superhost, y=price)) + 
      geom_point( aes(color=host_is_superhost)) + geom_smooth(method = "glm") +
      scale_x_discrete(name ="If/not Superhost",labels=c("f"="No" ,"t"="Yes")) +   
      scale_y_continuous(name = "price ($)", breaks = seq(0, 1000, by = 100))+ theme_bw() +
      ggtitle("Price over Superhost in LA") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(colour="black", size = 10),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))
```

### Price ~ Property type
```{r}
###property type in LA
airbnb_la_room <- airbnb_la %>% filter(price > 0 & price <= 1000) %>% dplyr::select(property_type, bedrooms, price)
room_la <- airbnb_la_room  %>% group_by(property_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(room_la, aes(y=mean_price, x = 
                     reorder(x=property_type,-mean_price),
                     fill=as.factor(property_type))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Property Type in LA") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different property in LA") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))


###property type in NY
airbnb_ny_room <- airbnb_ny %>% filter(price > 0 & price <= 1000) %>% dplyr::select(property_type, bedrooms, price)
room_ny <- airbnb_ny_room  %>% group_by(property_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(room_ny, aes(y=mean_price, x = 
                     reorder(x=property_type,-mean_price),
                     fill=as.factor(property_type))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Property Type in NYC") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different property in NYC") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))


###property type in seattle
airbnb_se_room <- airbnb_se %>% filter(price > 0 & price <= 1000) %>% dplyr::select(property_type, bedrooms, price)
room_se <- airbnb_se_room  %>% group_by(property_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(room_se, aes(y=mean_price, x = 
                     reorder(x=property_type,-mean_price),
                     fill=as.factor(property_type))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Property Type in Seattle") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different property in Seattle") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))



###property type in Vancouver
airbnb_va_room <- airbnb_va %>% filter(price > 0 & price <= 1000) %>% dplyr::select(property_type, bedrooms, price)
room_va <- airbnb_va_room  %>% group_by(property_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(room_va, aes(y=mean_price, x = 
                     reorder(x=property_type,-mean_price),
                     fill=as.factor(property_type))) + 
      geom_bar(stat="identity", fill="pink", position = "dodge") +  
      scale_x_discrete(name ="Property Type in Vancouver") +   
      scale_y_continuous(name = "Mean price ($)", breaks = seq(0, 1000, by = 50))+ theme_bw() +
      ggtitle("Price over different property in Vancouver") +  
      theme(axis.title.x = element_text(face="bold",  size=14), 
            axis.title.y = element_text(face="bold",  size=14),
            plot.title = element_text(size=16, face="bold"),
            axis.text.x=element_text(angle=90, colour="black", size = 8),
            axis.text.y=element_text(colour="black", size = 10)) +
      theme(plot.title = element_text(hjust = 0.5))

```

### Price ~ room type
```{r}
## Room type in LA
airbnb_la_type <- airbnb_la %>% filter(price > 0 & price <= 1000) %>% dplyr::select(room_type, bedrooms, price)
type_la <- airbnb_la_type  %>% group_by(room_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(type_la, aes(y=mean_price, x=room_type, fill=room_type)) + 
      geom_bar(stat="identity") + scale_fill_brewer(palette = "RdPu") +
      scale_x_discrete(name ="Different Room Type") + 
      scale_y_continuous(name="price($)", breaks = seq(0, 1000, by = 50)) + 
      ggtitle("Price over Different Room type in LA") + 
      theme_bw() +
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),  
            axis.text.x  = element_text( vjust=0.5, size=10)) +
      theme(plot.title = element_text(hjust = 0.5))


## Room type in NY
airbnb_ny_type <- airbnb_ny %>% filter(price > 0 & price <= 1000) %>% dplyr::select(room_type, bedrooms, price)
type_ny <- airbnb_ny_type  %>% group_by(room_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(type_ny, aes(y=mean_price, x=room_type, fill=room_type)) + 
      geom_bar(stat="identity") + scale_fill_brewer(palette = "RdPu") +
      scale_x_discrete(name ="Different Room Type") + 
      scale_y_continuous(name="price($)", breaks = seq(0, 1000, by = 50)) + 
      ggtitle("Price over Different Room type in NYC") + 
      theme_bw() +
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),  
            axis.text.x  = element_text( vjust=0.5, size=10)) +
      theme(plot.title = element_text(hjust = 0.5))


## Room type in Seattle
airbnb_se_type <- airbnb_se %>% filter(price > 0 & price <= 1000) %>% dplyr::select(room_type, bedrooms, price)
type_se <- airbnb_se_type  %>% group_by(room_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(type_se, aes(y=mean_price, x=room_type, fill=room_type)) + 
      geom_bar(stat="identity") + scale_fill_brewer(palette = "RdPu") +
      scale_x_discrete(name ="Different Room Type") + 
      scale_y_continuous(name="price($)", breaks = seq(0, 1000, by = 50)) + 
      ggtitle("Price over Different Room type in Seattle") + 
      theme_bw() +
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),  
            axis.text.x  = element_text( vjust=0.5, size=10)) +
      theme(plot.title = element_text(hjust = 0.5))


## Room type in Vancouver
airbnb_va_type <- airbnb_va %>% filter(price > 0 & price <= 1000) %>% dplyr::select(room_type, bedrooms, price)
type_va <- airbnb_va_type  %>% group_by(room_type) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(type_va, aes(y=mean_price, x=room_type, fill=room_type)) + 
      geom_bar(stat="identity") + scale_fill_brewer(palette = "RdPu") +
      scale_x_discrete(name ="Different Room Type") + 
      scale_y_continuous(name="price($)", breaks = seq(0, 1000, by = 50)) + 
      ggtitle("Price over Different Room type in Vancouver") + 
      theme_bw() +
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold"),  
            axis.text.x  = element_text( vjust=0.5, size=10)) +
      theme(plot.title = element_text(hjust = 0.5))
```

### Accomodations ~ Price
```{r}
airbnb_se_acc <- airbnb_se %>% filter(price > 0 & price <= 1000) %>% dplyr::select(accommodates, price)
acc_se <- airbnb_se_acc  %>% group_by(accommodates) %>% summarise(mean_price = mean(price)) %>% arrange(desc(mean_price))
ggplot(acc_se, aes(y=mean_price, x=accommodates,fill=as.factor(accommodates))) + 
      geom_bar(stat="identity", fill="pink") +  
      scale_x_continuous(name = "No. of Accommodates", breaks = seq(0, 50, by = 1)) +   
      scale_y_continuous(name = "Mean price", breaks = seq(0, 1000, by = 100))+ theme_bw()+
      ggtitle("Price over number of Accommodates in Seattle") +  
      theme(axis.title.x = element_text(face="bold",  size=12), 
            axis.title.y = element_text(face="bold",  size=12),
            plot.title = element_text(size=14, face="bold")) +
      theme(plot.title = element_text(hjust = 0.5))


```



```{r}
hotel <- read.csv2("hotels.csv", header = TRUE, sep = ";", dec = ",")
View(hotel)


```

